/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alertas` | `/alertas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/buscar` | `/buscar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favoritos` | `/favoritos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mapa` | `/mapa`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/alertas` | `/alertas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/buscar` | `/buscar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/favoritos` | `/favoritos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mapa` | `/mapa`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/alertas${`?${string}` | `#${string}` | ''}` | `/alertas${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/buscar${`?${string}` | `#${string}` | ''}` | `/buscar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/favoritos${`?${string}` | `#${string}` | ''}` | `/favoritos${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mapa${`?${string}` | `#${string}` | ''}` | `/mapa${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alertas` | `/alertas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/buscar` | `/buscar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favoritos` | `/favoritos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mapa` | `/mapa`; params?: Router.UnknownInputParams; };
    }
  }
}
