import {
  AlertPreference,
  MarketKpi,
  MarketSummary,
  ModerationItem,
  Offer,
  PlanOverview,
  PlatformKpi,
  PlatformUser,
  ProductComparison,
  RolePermissions,
  UserRole,
} from "@/features/shared/types";

export const ROLE_PERMISSIONS: RolePermissions = {
  super_admin: [
    "dashboard:market:view",
    "dashboard:global:view",
    "offer:view",
    "offer:create",
    "offer:edit",
    "offer:publish",
    "market:manage",
    "user:manage",
    "plan:manage",
    "moderation:manage",
    "importer:use",
  ],
  admin_mercado: [
    "dashboard:market:view",
    "offer:view",
    "offer:create",
    "offer:edit",
    "offer:publish",
    "importer:use",
  ],
};

export const mockMarkets: MarketSummary[] = [
  {
    id: "mk-carol-matao",
    name: "Carol Supermercado",
    city: "Matão",
    state: "SP",
    status: "ativo",
    plan: "Pro",
    activeOffers: 124,
    monthlyViews: 18420,
    monthlyClicks: 6290,
    conversionRate: 34.1,
  },
  {
    id: "mk-maisbarato-araraquara",
    name: "Mais Barato Araraquara",
    city: "Araraquara",
    state: "SP",
    status: "ativo",
    plan: "Enterprise",
    activeOffers: 210,
    monthlyViews: 28400,
    monthlyClicks: 11040,
    conversionRate: 38.9,
  },
  {
    id: "mk-bomdia-ribeirao",
    name: "Bom Dia Ribeirão",
    city: "Ribeirão Preto",
    state: "SP",
    status: "pendente",
    plan: "Free",
    activeOffers: 48,
    monthlyViews: 5200,
    monthlyClicks: 1210,
    conversionRate: 23.3,
  },
  {
    id: "mk-santa-fe-sao-carlos",
    name: "Santa Fé São Carlos",
    city: "São Carlos",
    state: "SP",
    status: "suspenso",
    plan: "Pro",
    activeOffers: 0,
    monthlyViews: 0,
    monthlyClicks: 0,
    conversionRate: 0,
  },
];

export const mockPlatformKpis: PlatformKpi[] = [
  {
    id: "kpi-mercados",
    label: "Mercados ativos",
    value: "78",
    trend: "up",
    delta: "+12% no mês",
  },
  {
    id: "kpi-usuarios",
    label: "Consumidores ativos",
    value: "32.4k",
    trend: "up",
    delta: "+8.1% no mês",
  },
  {
    id: "kpi-ofertas",
    label: "Ofertas publicadas",
    value: "4.982",
    trend: "up",
    delta: "+5.4% no mês",
  },
  {
    id: "kpi-economia",
    label: "Economia gerada",
    value: "R$ 218 mil",
    trend: "stable",
    delta: "estável em 30 dias",
  },
];

export const mockGlobalComparisons: ProductComparison[] = [
  {
    productName: "Detergente 500ml",
    bestPrice: 1.89,
    worstPrice: 2.89,
    marketWithBestPrice: "Carol Supermercado",
    marketWithWorstPrice: "Bom Dia Ribeirão",
  },
  {
    productName: "Arroz Tipo 1 5kg",
    bestPrice: 24.99,
    worstPrice: 31.49,
    marketWithBestPrice: "Mais Barato Araraquara",
    marketWithWorstPrice: "Santa Fé São Carlos",
  },
  {
    productName: "Leite Integral 1L",
    bestPrice: 4.29,
    worstPrice: 5.39,
    marketWithBestPrice: "Carol Supermercado",
    marketWithWorstPrice: "Bom Dia Ribeirão",
  },
];

export const mockMarketKpisByMarket: Record<string, MarketKpi[]> = {
  "mk-carol-matao": [
    { id: "mkv-1", label: "Ofertas ativas", value: "124", helper: "18 novas nesta semana" },
    { id: "mkv-2", label: "Cliques em ofertas", value: "6.290", helper: "+11% vs mês passado" },
    { id: "mkv-3", label: "Taxa de conversão", value: "34,1%", helper: "acima da média da cidade" },
    { id: "mkv-4", label: "Receita estimada", value: "R$ 68.4k", helper: "origem: campanhas e orgânico" },
  ],
  "mk-maisbarato-araraquara": [
    { id: "mkv-5", label: "Ofertas ativas", value: "210", helper: "26 novas nesta semana" },
    { id: "mkv-6", label: "Cliques em ofertas", value: "11.040", helper: "+17% vs mês passado" },
    { id: "mkv-7", label: "Taxa de conversão", value: "38,9%", helper: "top 5 da plataforma" },
    { id: "mkv-8", label: "Receita estimada", value: "R$ 113.2k", helper: "origem: boost + busca" },
  ],
  "mk-bomdia-ribeirao": [
    { id: "mkv-9", label: "Ofertas ativas", value: "48", helper: "3 novas nesta semana" },
    { id: "mkv-10", label: "Cliques em ofertas", value: "1.210", helper: "em fase de ativação" },
    { id: "mkv-11", label: "Taxa de conversão", value: "23,3%", helper: "abaixo da média da cidade" },
    { id: "mkv-12", label: "Receita estimada", value: "R$ 12.8k", helper: "potencial de crescimento" },
  ],
  "mk-santa-fe-sao-carlos": [
    { id: "mkv-13", label: "Ofertas ativas", value: "0", helper: "conta suspensa" },
    { id: "mkv-14", label: "Cliques em ofertas", value: "0", helper: "conta suspensa" },
    { id: "mkv-15", label: "Taxa de conversão", value: "0%", helper: "conta suspensa" },
    { id: "mkv-16", label: "Receita estimada", value: "R$ 0", helper: "conta suspensa" },
  ],
};

export const mockOffersByMarket: Record<string, Offer[]> = {
  "mk-carol-matao": [
    {
      id: "ofr-1001",
      marketId: "mk-carol-matao",
      productName: "Detergente Ypê 500ml",
      brand: "Ypê",
      category: "Limpeza",
      unit: "un",
      price: 1.99,
      listPrice: 3.5,
      discountPercent: 43,
      validUntil: "2026-02-28",
      verified: true,
      status: "ativa",
      source: "manual",
      createdAt: "2026-01-11",
      note: "43% abaixo da média da região",
    },
    {
      id: "ofr-1002",
      marketId: "mk-carol-matao",
      productName: "Arroz Tio João 5kg",
      brand: "Tio João",
      category: "Mercearia",
      unit: "un",
      price: 24.99,
      listPrice: 29.9,
      discountPercent: 16,
      validUntil: "2026-02-21",
      verified: true,
      status: "ativa",
      source: "manual",
      createdAt: "2026-01-14",
    },
    {
      id: "ofr-1003",
      marketId: "mk-carol-matao",
      productName: "Leite Integral Piracanjuba 1L",
      brand: "Piracanjuba",
      category: "Laticínios",
      unit: "un",
      price: 4.29,
      listPrice: 5.19,
      discountPercent: 17,
      validUntil: "2026-02-16",
      verified: true,
      status: "ativa",
      source: "manual",
      createdAt: "2026-01-14",
    },
  ],
  "mk-maisbarato-araraquara": [
    {
      id: "ofr-2001",
      marketId: "mk-maisbarato-araraquara",
      productName: "Banana Prata kg",
      brand: "Hortifruti",
      category: "Hortifruti",
      unit: "kg",
      price: 3.49,
      listPrice: 5.99,
      discountPercent: 42,
      validUntil: "2026-02-20",
      verified: true,
      status: "ativa",
      source: "manual",
      createdAt: "2026-01-13",
    },
  ],
  "mk-bomdia-ribeirao": [
    {
      id: "ofr-3001",
      marketId: "mk-bomdia-ribeirao",
      productName: "Óleo de Soja 900ml",
      brand: "Soya",
      category: "Mercearia",
      unit: "un",
      price: 6.99,
      listPrice: 7.99,
      discountPercent: 12,
      validUntil: "2026-02-14",
      verified: false,
      status: "rascunho",
      source: "manual",
      createdAt: "2026-01-22",
    },
  ],
  "mk-santa-fe-sao-carlos": [],
};

export const mockPlatformUsers: PlatformUser[] = [
  {
    id: "usr-1",
    name: "Lucas Galhardo",
    email: "lucas@precomapa.com",
    role: "super_admin",
    status: "ativo",
    lastAccess: "2026-02-09 11:14",
  },
  {
    id: "usr-2",
    name: "Ana Martins",
    email: "ana@precomapa.com",
    role: "analista",
    status: "ativo",
    lastAccess: "2026-02-09 09:48",
  },
  {
    id: "usr-3",
    name: "Pedro Costa",
    email: "pedro@precomapa.com",
    role: "suporte",
    status: "inativo",
    lastAccess: "2026-02-07 17:05",
  },
];

export const mockModerationQueue: ModerationItem[] = [
  {
    id: "mod-1",
    marketName: "Bom Dia Ribeirão",
    offerName: "Picanha Friboi 1kg",
    reason: "Preço muito abaixo do histórico",
    createdAt: "2026-02-08 14:33",
    status: "pendente",
  },
  {
    id: "mod-2",
    marketName: "Santa Fé São Carlos",
    offerName: "Detergente 500ml",
    reason: "Oferta duplicada em lote",
    createdAt: "2026-02-08 10:15",
    status: "pendente",
  },
  {
    id: "mod-3",
    marketName: "Carol Supermercado",
    offerName: "Leite Integral 1L",
    reason: "Validade inconsistente",
    createdAt: "2026-02-07 16:54",
    status: "aprovado",
  },
];

export const mockPlanOverview: PlanOverview[] = [
  {
    id: "pln-1",
    marketName: "Carol Supermercado",
    plan: "Pro",
    amount: "R$ 299,00",
    renewalDate: "2026-03-04",
    status: "ativo",
  },
  {
    id: "pln-2",
    marketName: "Mais Barato Araraquara",
    plan: "Enterprise",
    amount: "R$ 890,00",
    renewalDate: "2026-03-12",
    status: "ativo",
  },
  {
    id: "pln-3",
    marketName: "Bom Dia Ribeirão",
    plan: "Free",
    amount: "R$ 0,00",
    renewalDate: "-",
    status: "trial",
  },
];

export const mockAlertPreferences: AlertPreference[] = [
  {
    id: "alrt-1",
    title: "Leite Integral até R$ 4,49",
    category: "Laticínios",
    maxPrice: 4.49,
    isEnabled: true,
  },
  {
    id: "alrt-2",
    title: "Arroz 5kg até R$ 25,99",
    category: "Mercearia",
    maxPrice: 25.99,
    isEnabled: true,
  },
  {
    id: "alrt-3",
    title: "Detergente até R$ 2,20",
    category: "Limpeza",
    maxPrice: 2.2,
    isEnabled: false,
  },
];

export const defaultSessionByRole: Record<UserRole, { userName: string; userEmail: string; availableMarketIds: string[] }> = {
  super_admin: {
    userName: "Lucas Galhardo",
    userEmail: "lucas@precomapa.com",
    availableMarketIds: mockMarkets.map((market) => market.id),
  },
  admin_mercado: {
    userName: "Gerente Carol",
    userEmail: "admin@carolsuper.com.br",
    availableMarketIds: ["mk-carol-matao"],
  },
};
